# GET http://127.0.0.1:5000 HTTP/1.1

# POST http://127.0.0.1:8001/signup-student HTTP/1.1
# content-type: application/json

# {
# "studentName":"Sethubharathi B",
# "studentEmail":"1905113cse@cit.edu.in",
# "studentPassword":"123456",
# "studentDepartment":"CSE"
# }

# POST http://127.0.0.1:8001/signup-teacher HTTP/1.1
# content-type: application/json

# {
# "teacherName":"Admin",    
# "teacherEmail":"admin@gmail.com",
# "teacherPassword":"123456",
# "teacherDepartment":"-",
# "isAdmin":true
# }

# POST http://127.0.0.1:8001/login-student HTTP/1.1
# content-type: application/json

# {
# "studentEmail":"loganvk18@gmail.com",
# "studentPassword":"123456"
# }

# Admin
# POST http://127.0.0.1:8001/login-teacher HTTP/1.1
# content-type: application/json

# {
# "teacherEmail":"admin@gmail.com",
# "teacherPassword":"123456"
# }

# Teacher
# POST http://127.0.0.1:8001/login-teacher HTTP/1.1
# content-type: application/json

# {
# "teacherEmail":"logan123456@gmail.com",
# "teacherPassword":"12345678910"
# }

# POST http://127.0.0.1:8001/login-teacher HTTP/1.1
# content-type: application/json

# {
# "file":"",
# "subjectName":"Operating system",
# "type":"Note",
# "description":"Lorem ejfnjcd cednkjcd wdcjnwdc dsieiru cdshve fehubda ",
# "topics":["different types of os","memory management","storage management","algorithms"],
# "upVotes":[],
# "downVotes":[],
# "uId":"HSLKu9AN3XWczoVFIql7FnLYAPy2",
# "datePublished":"20/12/2022"
# "userType":"student"
# }


# POST http://127.0.0.1:8001/note-accept HTTP/1.1
# content-type: application/json

# {
#     "voterId":"0nXlteUZcpbZUbzi4N8cOez1Mls2",
#     "userId":"zWK7QqUwKdZXYlvzWdyF0zNso0I3",
#     "noteId":"1sFyXEyXxiUL-JKDAlAYsFHpmsOeb0F2m"
# }

# GET http://127.0.0.1:8001/get-all-notes HTTP/1.1 

# POST http://127.0.0.1:8001/update-votes HTTP/1.1
# content-type: application/json

# {
#     "noteId":"1PGfclHeez8pPqOL37oZqYiXPFK6H5s9w",
#     "downVotes":[],
#     "upVotes":[{"id":"0nXlteUZcpbZUbzi4N8cOez1Mls2","userType":"student"}]
# }

# GET http://127.0.0.1:8001//get-all-notes-admin HTTP/1.1 

# POST http://127.0.0.1:8001/update-note-admin HTTP/1.1
# content-type: application/json

# {
#     "noteId":"1507LOULfuCVTFOeHRP1OgWimwquctjud",
#     "type":"reject"
# }


# POST http://127.0.0.1:8001/update-votes HTTP/1.1
# content-type: application/json

# {
#     "noteId":"1sFyXEyXxiUL-JKDAlAYsFHpmsOeb0F2m",
#     "downVotes":[{"id":"0nXlteUZcpbZUbzi4N8cOez1Mls2","userType":"student"}],
#     "upVotes":[]
# }

# POST http://127.0.0.1:8001/get-faq-and-papers HTTP/1.1
# content-type: application/json

# {
#     "subjectName":"operating system",
#     "subjectCode":"19CS01",
#     "type":"midsemester"
# }

# POST http://127.0.0.1:8001/create-private-note HTTP/1.1
# content-type: application/json

# {
#    "data":"{noteContent:new content}",
#    "uId":"OPHrpIATWfat57q4sdmSYve1crC3"
# }
# POST http://127.0.0.1:8001//get-private-notes HTTP/1.1
# content-type: application/json

# {
#    "uId":"OPHrpIATWfat57q4sdmSYve1crC3"
# }

GET http://127.0.0.1:8001/get-all-list-of-faqs HTTP/1.1 


