# GET http://127.0.0.1:5000 HTTP/1.1

# POST http://127.0.0.1:5000/signup-student HTTP/1.1
# content-type: application/json

# {
# "studentName":"Loganathan",
# "studentEmail":"projectmain12345@gmail.com",
# "studentPassword":"123456",
# "studentDepartment":"CSE"
# }

# POST http://127.0.0.1:5000/signup-teacher HTTP/1.1
# content-type: application/json

# {
# "teacherName":"Loganathan",
# "teacherEmail":"logan123456@gmail.com",
# "teacherPassword":"12345678910",
# "teacherDepartment":"CSE"
# }

# POST http://127.0.0.1:5000/login-student HTTP/1.1
# content-type: application/json

# {
# "studentEmail":"logan12@gmail.com",
# "studentPassword":"12345678910"
# }


# POST http://127.0.0.1:5000/login-teacher HTTP/1.1
# content-type: application/json

# {
# "teacherEmail":"logan123456@gmail.com",
# "teacherPassword":"12345678910"
# }

# POST http://127.0.0.1:5000/login-teacher HTTP/1.1
# content-type: application/json

# {
# "file":"",
# "subjectName":"Operating system",
# "type":"Note",
# "description":"Lorem ejfnjcd cednkjcd wdcjnwdc dsieiru cdshve fehubda ",
# "topics":["different types of os","memory management","storage management","algorithms"],
# "upVotes":[],
# "downVotes":[],
# "uId":"HSLKu9AN3XWczoVFIql7FnLYAPy2",
# "datePublished":"20/12/2022"
# "userType":"student"
# }


POST http://127.0.0.1:5000/note-accept HTTP/1.1
content-type: application/json

{
    "voterId":"kCBXdBD1xzNaElDhxfjAVwG88Wo2",
    "userId":"zWK7QqUwKdZXYlvzWdyF0zNso0I3",
    "noteId":"16UDqyzPrm6VG89jd2OmPvgkmzu9_W04B"
}